### ISSUE TITLE
Python 3 not supported

### ISSUE THREAD

**Issue by Matt-Deacalion** [jrief/django-sass-processor#10]

**Comment by frostbtn** [comment]
Status update. I use version 0.2.5 with Python 3.4. 
No problems in basic scenarios: online and offline compilation.

**Comment by mayoroftuesday** [comment]
I'm also having trouble in python3. For instance, in compilescss.py(129)compile(), the output file needs to be opened with 'wb' to force it into byte-mode, not just 'w'.

**Comment by frostbtn** [comment]
@mayoroftuesday. Yeah, it is fixed in master. Waiting @jrief to release 0.3.0 for us.

**Comment by jrief** [comment]
@frostbtn thanks for reminding me - version 0.3.0 is published
