### ISSUE TITLE
autoprefixer with compilescss

### ISSUE THREAD

**Issue by pegler** [jrief/django-sass-processor#100]
We just tried setting up autoprefixing our scss, but it doesn't seem to be working with compilescss. I looked through the code and it looks like compilescss calls libsass directly instead of going through the SassProcessor class. Is it expected that compilescss should call autoprefix? If so, I will dig in more to debug what is going on.

django-sass-processor==0.7
libsass==0.14.5

**Comment by pegler** [comment]
I wrote a quick pull to add support for this: https://github.com/jrief/django-sass-processor/pull/101

Perhaps the autoprefixer calling code should be moved to a helper function that both SassProcessor and the compilescss could use.

**Comment by jrief** [comment]
You can use `postcss`. Please refer to the docs on how to use it.
