### ISSUE TITLE
css file preferred over source file while DEBUG=True

### ISSUE THREAD

**Issue by elmcrest** [jrief/django-sass-processor#102]
hey,

I'm not sure if this is intentional or not so I'm describing what just hit me.

If you have used compilescss locally to prepare deployment, sass-processor places a compiled css file right next to the scss source in my case.
Now, if that css file exists, it gets served by runserver no matter if the source changes or not.

I tried to pin this behaviour in the code but couldn't find it, I was suspecting resolve_path should be involved but I can't really tell, sorry.

so, to me this feels like an issue which should be addressed to one of two options:
1. just prefered source file (might lead to other issues in different use cases though)
2. throw a warning in this particular case so it doesn't take long to catch it

let me know what you think and thanks for django-sass-processor in general, helps me a lot.

edit: for now I'm just using the `--delete-files` flag with another `compilescss` call, I guess that's expected to use. hmm, maybe this issue is pointless, still I'd bet I'm not the only one running into this :smile:

**Comment by jrief** [comment]
> If you have used compilescss locally to prepare deployment, sass-processor places a compiled css file right next to the scss source in my case.

this is intended behaviour, afterward you run `manage.py collectstatic`

> Now, if that css file exists, it gets served by runserver no matter if the source changes or not.

you should not use `runserver` in production

the command `manage.py compilescss --delete-files` is intended for this purpose

**Comment by elmcrest** [comment]
yeah, I'm using whitenoise on production and for my little load it's fast enough... if I'm running into issues I will upgrade to a CDN. Anyways, back to the issue:

the issue was while working locally, so my deployment was:
```
1. compilescss
2. collectstatic
3. docker build
```
but I didn't had the needed additional call with the `--delete-files` flag, so the next time developing locally the css files were served silently. this was surprising to me and took some time to figure.
so, now I've just added another step
```
4. compilescss --delete-files
```
and now it works fine :)

my point still is, isn't it worth, in case it's easily doable, to add a console warning for this?

**Comment by jrief** [comment]
> my point still is, isn't it worth, in case it's easily doable, to add a console warning for this?

you mean after issuing the management command? Hmm, why not creating a command option which compiles+collects+deletes the files. Would be pretty easy to implement. Any suggestion how to name this option?

**Comment by jrief** [comment]
why not automate, what can be automated. How about `compilescss --collectstatic-and-remove`?

**Comment by elmcrest** [comment]
Sure, sounds like an good improvement to me. Also I prefer clear names for things compared to unclear shortcuts.

**Comment by elmcrest** [comment]
Hey again,

meanwhile I‘ve realised that your suggestion isn‘t perfect for me, because `collectstatic` isn‘t called from the same python interpreter `compilescss` is.
In my case `compilescss` is called as part of a ‚deployment setup‘ from the local interpreter but `collectstatic` from the ‚production‘ interpreter inside a container with a different django settings module...
Sure I could make those compatible but it‘s introducting some inflexibility...

Just another perspective to think about.

**Comment by jrief** [comment]
so it's probably better if you do it "manually" and we leave everything as it currently is.

**Comment by elmcrest** [comment]
Yes
