### ISSUE TITLE
Compiled CSS files not served in development

### ISSUE THREAD

**Issue by jfschaff** [jrief/django-sass-processor#107]
I followed the readme, the css files are generated from the scss files, but when I use python manage.py runserver, I get a 404 (Not Found) error for the css files.

Any idea where this could come from ?

Could there be an issue with 'sass_processor.finders.CssFinder'?

**Comment by jrief** [comment]
This is a typical FAQ:

django-sass-processor is shipped with a special finder, to locate the generated *.css files in the directory referred by SASS_PROCESSOR_ROOT (or, if unset STATIC_ROOT). Just add it to your settings.py. If there is no STATICFILES_FINDERS in your settings.py don't forget to include the Django default finders.

If the directory referred by SASS_PROCESSOR_ROOT does not exist, then django-sass-processor creates it. This does does not apply, if SASS_PROCESSOR_ROOT is unset and hence defaults to STATIC_ROOT. Therefore it is a good idea to otherwise use SASS_PROCESSOR_ROOT = STATIC_ROOT in your settings.py.

**Comment by jfschaff** [comment]
Thank you for your answer. As I wrote, I have read and followed the readme.md. My `settings.py` already includes the following definitions:

```
STATIC_FILES_FINDER = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'sass_processor.finders.CssFinder',
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
SASS_PROCESSOR_ROOT = STATIC_ROOT
```
When I run the dev server (`python manage.py runserver`) the proper CSS files are produced in the `STATIC_ROOT` directory, but not served.

Am I still missing something here?

**Comment by jrief** [comment]
> When I run the dev server the proper CSS files are produced in the STATIC_ROOT directory, but not served.

These files actually are served by Django and not by this app. Did you forget to set `DEBUG = True`? Did you add `django.contrib.staticfiles` to INSTALLED_APPS?

Again, this is not a problem of **django-sass-processor**.

**Comment by jfschaff** [comment]
Yes, I do have `DEBUG = True`, and other static files (not generated by django-sass-processor) are properly served.

There might be some kind of conflict between static paths though (see project files and folders below): could the `api/static/` dir somehow "conflict" with the `api/website/static/` dir?

```
api
├── api
│   ├── ...
...
├── static
│   └── website
│       └── assets
│           ├── test.css
│           └── test.css.map
└── website
    ├── admin.py
    ├── apps.py
    ├── __init__.py
    ├── migrations
...
    ├── models.py
    ├── static
    │   └── website
    │       └── assets
    │           ├── bootstrap.min.css
    │           ├── bootstrap.min.js
    │           ├── test.scss
    │           ├── jquery-3.2.1.min.js
    │           ├── popper.min.js
    │           └── style.css
    ├── templates
    │   └── website
    │       └── base.html
    ├── tests.py
    ├── urls.py
    └── views.py
```

**Comment by jrief** [comment]
> Yes, I do have DEBUG = True, and other static files (not generated by django-sass-processor) are properly served.

But presumably they are served by the `AppDirectoriesFinder`. Files in `STATICFILES_DIR` are found by the `FileSystemFinder`. In Django the directory specified by `STATICFILES_DIR` is rarely required, and if, only by projects, never by apps. Put some dummy files in there and try if you can access them directly.
