### ISSUE TITLE
Unresolved tag 'sass_src'

### ISSUE THREAD

**Issue by mdczaplicki** [jrief/django-sass-processor#109]
I got this error in my template.  
I use Python 3.6 and Django 2.1.  
I ran this: `pip install libsass django-compressor django-sass-processor`
I have added `'sass_processor'` to `INSTALLED_APPS`.  
I have added `'sass_processor.finders.CssFinder',` to `STATICFILES_FINDERS`.  
I have also included my static dir in `SASS_PROCESSOR_INCLUDE_DIRS`.

**Comment by jrief** [comment]
Add `{% load sass_tags %}` to your template.
This is well explained in the docs.
