### ISSUE TITLE
problem resolving ~ imports

### ISSUE THREAD

**Issue by neoflex** [jrief/django-sass-processor#113]
Hi,

I have the following error that I don't manage to solve:

```
Error: File to import not found or unreadable: ~bootstrap/scss/functions. on line 56 of web/static/vendor/node_modules/bootstrap-material-design/scss/_variables.scss from line 2 of web/static/vendor/node_modules/bootstrap-material-design/scss/_core.scss from line 3 of web/static/vendor/node_modules/bootstrap-material-design/scss/bootstrap-material-design.scss from line 2 of web/static/css/myproject.scss >> @import "~bootstrap/scss/functions"; // from bootstrap node_module ^
```

Apparently, the use of ~ results in an unresolved path here.
My folder structure:

- project
   - app1
   - app2
      - static
          - css
              - myproject.scss
          - vendor
               - node_modules
                   - bootstrap-material-design
                   - bootstrap
   - static
         - myproject.css (generated)

in my template:

```html
<link href="{% sass_src 'css/myproject.scss' %}" rel="stylesheet" type="text/css"/>
````

myproject.scss:

```sass
@import "../vendor/node_modules/bootstrap-material-design/scss/bootstrap-material-design";
```

Any suggestion? I tried to play with the different settings parameters but without any success.

**Comment by jrief** [comment]
please refer to #112, that answer applies to your problem too.

**Comment by neoflex** [comment]
thanks for your answer.
I don't think it's the same issue.
Here the problem seems to be the lack of support for the 'importers' parameter of libsass. See https://github.com/matthewdavidson/node-sass-tilde-importer as an example of how it was done for node-sass. That seems to be why imports using ~ are not resolved.

**Comment by jrief** [comment]
did you try to configure your SASS import search path. I, for instance add

```
SASS_PROCESSOR_INCLUDE_DIRS = [
    os.path.join(BASE_DIR, 'node_modules'),
]
```

to my settings.py
