### ISSUE TITLE
Generate and reload css files doesn't work in debug mode. 

### ISSUE THREAD

**Issue by sophiekovalevsky** [jrief/django-sass-processor#114]
Thanks for taking the time to develop this amazing app. 

I know that there have been some issues concerning to this topic, however, while I was trying to figure it out this on my own it did work out, then I decided to write after running out of possible solutions that could fix my problem. 

I would like to generate my sass files in debug mode and instantly see the changes on my browser without reload the page. If I am right this is the main aim of this plugin based on the documentation  provided. Then, after following up the instructions in README file, I am not able to make it work. :/ 

This is what I have setup in settings.py:
DEBUG = True
SASS_PROCESSOR_ENABLED = True
SASS_PROCESSOR_ROOT = os.path.join(BASE_DIR, 'kiaranavarro', 'sass')
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'sass_processor.finders.CssFinder'
]

Then, within a view with the specific path: myapp/kiaranavarro/templates/base.html:
{% load sass_tags %}
<link href="{% sass_src 'main.scss' %}" rel="stylesheet" type="text/css" />

When I try to access my server I got this message:
Unable to locate file main.scss while rendering tag 'sass_src' in template main.html

Using os.path.join(BASE_DIR, 'kiaranavarro', 'sass') should point out to folder where main.scss is stored and this is true. I confirmed that because if I do not create this folder beforehand and render the view, sass-processor create the folder where it is supposed to be. Then, with this I know that the path where SASS_PROCESSOR_ROOT is pointing it is the one I want it.

However, I do not still see why it doesn't load my sass file. Within my sass file I am not importing any other file, BTW.

One thing that I am thinking is that maybe, as my folder it is not within the static root, django is not able to serve my css files and consequently not being able serve what sass_tags is trying to look for.

Thanks in advance for the support.

**Comment by jrief** [comment]
If you want your browser to reload after a change in your code, you must use other tools, such as https://github.com/tjwalch/django-livereload-server
I would be interested myself, if that works for you.

**Comment by sophiekovalevsky** [comment]
@jrief thanks for your comments. I got it. I will take a closer look at. Cheers.
