### ISSUE TITLE
compilescss.Command.parse_template() can't find scss tags in extended DjangoTemplate

### ISSUE THREAD

**Issue by rtruxal** [jrief/django-sass-processor#119]
Hey there - I just poured through the `compilescss.py` module to figure out why I was "Sucessfully compil[ing] 0 referred SASS/SCSS files," and discovered the `walk_nodes()` function cannot see sass_tags unless they are top-level nodes. Moving my `{% sass_src 'scss/stylesheet.scss' %}` from `extended.html` into `base.html` solved it. 

I don't have time to make a pull request just now, but modifying `walk_nodes()` to look a little deeper, or explicitly requiring Django Template users to pay attention to where they put tags will probably fix this.

**Comment by jrief** [comment]
`walk_nodes` looks into all template directories of Django-apps mentioned in `INSTALLED_APPS`, or those mentioned explicitly in the `TEMPLATES['DIRS']` directories.

Therefore, unless one of those criteria is matched in your settings, I wouldn't consider it a bug. Please recheck.

**Comment by rtruxal** [comment]
Wait...are you sure `walk_nodes()` doesn't read html templates?
```
def parse_template(self, template_name):
        try:
            template = self.parser.parse(template_name)
        except IOError:  # unreadable file -> ignore
            ...<many error-catches>...
        try:
            nodes = list(self.walk_nodes(template, original=template)) #<===== ???????????????????????
            except Exception as e:
            # Could be an error in some base template
            if self.verbosity > 0:
                self.stderr.write("\nError parsing template {}: {}".format(template_name, e))
        else:
            for node in nodes:
                print(node.path)
                sass_filename = find_file(node.path)
                if not sass_filename or sass_filename in self.processed_files:
                    continue
                if self.delete_files:
                    self.delete_file(sass_filename, node.path)
                else:
                    self.compile_sass(sass_filename, node.path)```

**Comment by rtruxal** [comment]
I can probably fix it and make a pull-request when I get a bit of time, but if I'm misunderstanding the control-flow, please let me know what's going on in the above method.

**Comment by jrief** [comment]
Is template `extended.html` and `base.html` inside an app, referenced by `INSTALLED_APPS`?
Hint: Add a breakpoint to `compilescss.find_templates()` and check if your template is referenced in `paths`. Since templates are found by a standard Django-loader, please check for possible misconfiguration.

**Comment by rtruxal** [comment]
Good call! I hadn't properly referenced `extended.html`. Thanks for the tip!
