### ISSUE TITLE
Always getting TypeError at /

### ISSUE THREAD

**Issue by Xuton** [jrief/django-sass-processor#12]
I tried Python2 and Python3, but I keep getting the same problem on my view

TypeError at /
filename must be a string, not None
Request Method:	GET
Request URL:	http://127.0.0.1:8000/
Django Version:	1.8.5
Exception Type:	TypeError
Exception Value:	
filename must be a string, not None

I must have missed something, but I cannot figure out what it is.
I followed all the steps in the readme, but still having this issue.

I think it is not finding my scss file, but I cannot figure out which item in my settings.py relates to that file

Any advice?

PS: I dont think this is an issue per se, but rather me missing something in my config etc (Not sure how else to ask a question though)

**Comment by jrief** [comment]
I havn't tested with django-1.8, but that shouldn't be the reason.
Without backtrace its impossible to give any advise.

**Comment by Xuton** [comment]
I have asked a more comprehensive question here
http://stackoverflow.com/questions/33052553/django-sass-processor-typeerror
Not sure if that perhaps has sufficient information for assistance.

**Comment by frostbtn** [comment]
@Xuton, on SO you've posted:
```
STATICFILES_FINDERS = (
    'sass_processor.finders.CssFinder',
)
```
This disables **all** standard [django static finders](https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-STATICFILES_FINDERS). Me too had lost an hour on this: django-sass-processor's docs is not clear on this one. You should have at least:
```
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'sass_processor.finders.CssFinder',
)
```

**Comment by jrief** [comment]
Thanks @Xuton for this clarification. By using dots, I wanted to emphasize that other finders also must/can be added. Sorry for this inconvenience. I just changed the docs.
