### ISSUE TITLE
compilescss command doesn't work with django_jinja

### ISSUE THREAD

**Issue by pkqxdd** [jrief/django-sass-processor#124]
When the template loaders are set to `django_jinja` and django templates, `compilescss` command cannot find any templates associated with `django_jinja`.

**Comment by AndreasBackx** [comment]
What arguments are you passing to compilescss?

From the README:

> If you use an alternative templating engine set its name in --engine argument. Currently django and jinja2 are supported, see django-compressor documentation on how to set up COMPRESS_JINJA2_GET_ENVIRONMENT to configure jinja2 engine support.

**Comment by pkqxdd** [comment]
I passed `--engine jinja2` but apparently it doesn't work. Also, `django_jinja` is an alternative template loader build on top of `jinja2`, so it supports everything jinja2 supports

**Comment by AndreasBackx** [comment]
> Also, django_jinja is an alternative template loader build on top of jinja2, so it supports everything jinja2 supports

It's been a while since I've used django-sass-processor. But for one of my projects I remember making a fork, I'm unsure whether that's what made it work or not. Could you try using this fork of mine: https://github.com/AndreasBackx/django-jinja/tree/error-view-extensions

I'm also looking at an old project of mine and I used this configuration, take it for a spin I'd say:

```python
TEMPLATES = [
    {
        'BACKEND': 'django_jinja.backend.Jinja2',
        'APP_DIRS': True,
        'DIRS': [],
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
            ],
            'extensions': DEFAULT_EXTENSIONS + [
                'sass_processor.jinja2.ext.SassSrc',
                'compressor.contrib.jinja2ext.CompressorExtension',
            ],
            'match_extension': None,
            'default_extension': '.html',
            'app_dirname': 'jinja2',
        }
    }
]
```

**Comment by pkqxdd** [comment]
I've tried your fork and the same issue persists. `compilescss` outputs `Successfully compiled 0 referred SASS/SCSS files.`. 
Also here are my settings
```python
TEMPLATES = [
    {
        'BACKEND': 'django_jinja.backend.Jinja2',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'match_extension': '.jinja2',
            'extensions': DEFAULT_EXTENSIONS + [  # TODO: remove unnecessary extensions before production
                'compressor.contrib.jinja2ext.CompressorExtension',
                'website.jinja2ext.SpacelessExtension',
                'sass_processor.jinja2.ext.SassSrc'
            ],
            'constants': {
                'DEBUG': DEBUG
            },
            'globals': {
                'nav_root': 'nav.root',
            }
            
        },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
            ],
        },
    },

]
```

**Comment by AndreasBackx** [comment]
I'd look into this more, but I'm currently in my finals at university so I cannot set the needed time aside to look into it. Perhaps you could dive a bit into the source code and see where the problem lies?

**Comment by pkqxdd** [comment]
I think the problem is the `get_parser` function in `sass_processor.management.commands.compilescss`. It doesn't actually check the template configurations in settings but imports the parser rather naïvely. I think the problem can be fixed by changing the way it's implemented.
