### ISSUE TITLE
Prevent file exists error when creating SASS_PROCESSOR_ROOT

### ISSUE THREAD

**Issue by washeck** [jrief/django-sass-processor#125]
We encountered an issue when running manage.py commands in parallel. Running any manage.py command, e.g. `manage.py check` causes django-sass-processor to create `SASS_PROCESSOR_ROOT`. Unfortunatelly, there is a race condition in the code, see

https://github.com/jrief/django-sass-processor/blob/e54f2c4ae3f8fb7b795060a208ad4f1fd50627fc/sass_processor/finders.py#L25

If the directory does not exist on line 22 but another process creates it, the `os.makedirs()` fails with `FileExistsError: [Errno 17] File exists`

A simple fix is to change the call to `os.makedirs(location,  exist_ok=True)`

**Comment by jrief** [comment]
The problem with  `os.makedirs(location, exist_ok=True)` is that the optional argument `exist_ok` does not work in Python-2.7.
