### ISSUE TITLE
Sass compilation only happens twice and then stops working

### ISSUE THREAD

**Issue by ca1ek** [jrief/django-sass-processor#127]
The django-sass-processor settings I have are:
```
SASS_PROCESSOR_ENABLED = True
SASS_PROCESSOR_INCLUDE_FILE_PATTERN = r'^.+\.scss$'
```
I run my service in docker, but static files are still served by django in debug mode.
I set the file to be used with an admin panel view, trough Media
```
class Media:
    css = (static_hack(sass_processor('app/style.scss')),)
```
_static_hack is a workaround for another bug here, sass_processor gives a path with `/static/` in front, but Media expects a path without it, so I remove `/static/` from the beginning_

In `/project/app/static/app/style.scss` file I will put 
```
body { color: red; }
```
then reload the page, and a newly generated css will be shown. Then I change the file again
```
body { color: blue; }
```
and reload the page, and again, the new css is shown. I change the file the third time
```
body { color: green; }
```
And the file isn't recompiled, the old css is still shown, and no amount of changing will make the file recompile.

Removing the CSS file doesn't cause a recompile, only a 404 error happens.
`collectstatic`, then reloading doesn't cause a recompile.
Only way to get the page to recompile is to restart the server.

**Comment by jrief** [comment]
I don't know what `static_hack` is for and am somehow unsure if the Python AST-parser the detects the call to `sass_processor` properly.
Please retry by doing this in two steps and watch, if `compilescss` produces the correct file. Remember: This compiled file then is layed out side by side with the source, ie. it `xyz.scss` file.

**Comment by ca1ek** [comment]
Manually running compilescss works fine.
