### ISSUE TITLE
collectstatics ignore on apps.py

### ISSUE THREAD

**Issue by rsd** [jrief/django-sass-processor#128]
It would be nice to have ignore_pattern on apps.py by default.

e.g.
```python
from django.contrib.staticfiles.apps import StaticFilesConfig
class SassProcessorStaticConfig(AppConfig):
    ignore_patterns = ['CVS', '.*', '*~', '*.scss', '*.sass',]
```

**Comment by jrief** [comment]
`manage.py compilescss` only parses files ending in `.py`, so I don’t see any need for this feature. 
Maybe you can elaborate more on this.
