### ISSUE TITLE
Add Django 3 support

### ISSUE THREAD

**Issue by joren485** [jrief/django-sass-processor#131]
### Description
Django 3.0 was [released today](https://docs.djangoproject.com/en/3.0/releases/3.0/). Support for Django 3.0 should be added to `django-sass-processor`.

The removal of `django.utils.six` seems to be a breaking change. Django suggests to either remove the usage of `django.utils.six` (i.e. only support Python 3.6+) or to use `six` directly.

**Comment by codermrhasan** [comment]
As a novice, I have started a project few days ago depending on sass. Everything was fine. But suddenly I face this error during my work. I knew that Django 3.0 is coming. But I didn't notice that it was already released and that's the cause of my projects error. I have wasted 3 hours from my life. And then I actually figured it out. :(

**Comment by ShNURoK42** [comment]
> I have wasted 3 hours from my life.

Welcome to the world of programmers!

**Comment by merwok** [comment]
For applications, a good way to avoid this kind of problems is to always pin requirements: https://pypi.org/project/pip-tools/

**Comment by jrief** [comment]
There is a [pull request](https://github.com/jrief/django-sass-processor/pull/132) to support Django-3.0.
However, since **django-sass-processor** requires [django-compressor](https://github.com/django-compressor/django-compressor) and since that app does not yet support Django-3.0, we're out luck for now.
Moreover from my own experience, the maintainers of django-compressor are not the fastest in releasing new versions. So be prepared to either wait or use an unofficial image.

**Comment by davideghz** [comment]
this is pretty urgent

**Comment by jrief** [comment]
tell it to the maintainers of django-compressor but stop bothering me!

**Comment by debdolph** [comment]
> There is a [pull request](https://github.com/jrief/django-sass-processor/pull/132) to support Django-3.0.
> However, since **django-sass-processor** requires [django-compressor](https://github.com/django-compressor/django-compressor) and since that app does not yet support Django-3.0, we're out luck for now.
> Moreover from my own experience, the maintainers of django-compressor are not the fastest in releasing new versions. So be prepared to either wait or use an unofficial image.

https://github.com/django-compressor/django-compressor/pull/964

**Comment by jrief** [comment]
Just released version 0.8 which supports Django-3.0.
