### ISSUE TITLE
compilescss warnings when django-otp is present

### ISSUE THREAD

**Issue by fmgoncalves** [jrief/django-sass-processor#135]
[Django OTP](https://github.com/django-otp/django-otp) includes templates for several diffferent versions of Django, some of which are incompatible with other versions of Django. Since `python manage.py compilescss` tries to pick up any template file it can find, it will fail when processing some older templates:

```
Invalid template /usr/local/lib/python3.6/site-packages/django_otp/templates/otp/admin19/login.html: 'admin_static' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
countries
i18n
l10n
log
sass_tags
static
tz
```

**Comment by jrief** [comment]
... but this shall just print a warning message. Does it stop working in your environment?

**Comment by fmgoncalves** [comment]
You are absolutely right, I was thrown off by the bold red letters (from stderr in the shell) and nothing in the message saying warning. It does indeed ignore that template and the rest gets compiled fine. I have updated this issue's title to reflect that.

I am still leaving the PR as a suggestion, because to be honest having a warning on every deployment for a template that is out of my control (a dependency) and which I _know_ will never be used in any way is kind of annoying and misleading.

Thanks

**Comment by jrief** [comment]
You're right. From a UX point of view, **red bold** warnings are not OK. The red color comes from the exception thrown by the template compiler. Any ideas how to remove it?

I'm unsure, if it makes sense to add an `--exclude <pattern>` flag. I could imagine that excluding third party apps might make sense, but a globally applied pattern – hmm? Let's discuss more use cases.

**Comment by fmgoncalves** [comment]
To "fix" this UX wise, it might be enough to change the phrasing to make what's happening more obvious, like `Warning: template /usr/local/lib/python3.6/site-packages/django_otp/templates/otp/admin19/login.html uses an invalid tag library: admin_static` and add the list of possible tags at a higher verbosity level.

As for the exclude pattern, the fact that these templates cannot be ignored any other way despite the fact I know  they will never be used makes it extremely valuable for me for CD integration.
