### ISSUE TITLE
FILE_CHARSET is removed in Django 3.1

### ISSUE THREAD

**Issue by joren485** [jrief/django-sass-processor#138]
### Description
In Django 3.1 the `FILE_CHARSET` setting has been [removed](https://docs.djangoproject.com/en/3.1/releases/3.1/#features-removed-in-3-1) in favor of using [UTF-8 encoding for all files](https://docs.djangoproject.com/en/3.0/ref/settings/#file-charset).

This project uses `FILE_CHARSET` twice in [`compilescss.py`](https://github.com/jrief/django-sass-processor/blob/master/sass_processor/management/commands/compilescss.py).

**Comment by BojanKogoj** [comment]
Any chance this can be released soon?

**Comment by jrief** [comment]
Release 0.8.1 has this fix. Please recheck.

**Comment by BojanKogoj** [comment]
Thank you!
