### ISSUE TITLE
LibSass is deprecated

### ISSUE THREAD

**Issue by edoarad** [jrief/django-sass-processor#143]
According to https://sass-lang.com/blog/libsass-is-deprecated, LibSass is currently deprecated, and it is suggested to use [Dart Sass](https://sass-lang.com/dart-sass).

**Comment by jrief** [comment]
Hmm, these are bad news. Dart-SASS does not offer any Python bindings, and probably never will.
Therefore I would have to go through the system shell – something I really dislike. Currently you can call SASS functions written in Python directly out of your SASS file. I hardly can imagine that this will be possible with Dart-SASS.

-> wontfix

**Comment by longhotsummer** [comment]
Note to anyone who needs it, you can use https://github.com/laws-africa/django-sass-processor-dart-sass to get django-sass-processor to use dart sass.

**Comment by merwok** [comment]
> Therefore I would have to go through the system shell

You would have to use subprocesses, but not necessarily use a shell
