### ISSUE TITLE
Q: Compile to media storage instead of static?

### ISSUE THREAD

**Issue by Natureshadow** [jrief/django-sass-processor#146]
Hi,

we are using django-sass-processor in a probably rather atypical setup. We are using values stored in the database in our SCSS. Also, we need to recompile CSS when these settings change (ew do this by removing the compiled file in a `post_save` signal handler).

This results in a few inconvenient consequences:

* We cannot run `compilescss` before the database is available, i.e. at container/package build time
* We cannot run with a read-only `STATIC_ROOT`

We can easily ignore the first consequence and just not pre-compile.

For the second consequence, I came up with two approaches:

* Compile SCSS on every request, probably leveraging a cache
* Compile SCSS to the media file storage instead of `STATIC_ROOT`

Unfortunately, I failed to find out how to make django-sass-processor store the compiled file in the media storage, and how to deliver it from there.

Any hints on that, or new ideas how to approach the issue, are welcome!

**Comment by jrief** [comment]
> * Compile SCSS on every request, probably leveraging a cache

I wouldn't do that as compilation can take considerable time.

> * Compile SCSS to the media file storage instead of `STATIC_ROOT`

This is actually done when `DEBUG=True`. **django-sass-processor** compiles the css files into a directory outside of Git's control to avoid changing generated files. I usually do into a directory named  `workdir/static`positioned side-by side with `workdir/media`. A similar setup could be used for production though.

**Comment by Natureshadow** [comment]
> This is actually done when `DEBUG=True`. **django-sass-processor** compiles the css files into a directory outside of Git's control to avoid changing generated files. I usually do into a directory named `workdir/static`positioned side-by side with `workdir/media`. A similar setup could be used for production though.

But this will not work if media files uses some external storage, right?

**Comment by jrief** [comment]
> But this will not work if media files uses some external storage, right?

I'd have to check how media files are transferred to say AWS-S3, using the BOTO protocol. But there is certainly a way to do it. You can either create a pull request yourself, or hire me to do it, or wait until I need his feature myself.

**Comment by Natureshadow** [comment]
> I'd have to check how media files are transferred to say AWS-S3, using the BOTO protocol.

I'd rather use Django's File Storage API, ignoring what storage backend it uses.

**Comment by merwok** [comment]
> We cannot run compilescss before the database is available, i.e. at container/package build time

This problem sounds similar to the migration problem, and could be solved in the same way: deploy your code, then run a one-time command (migrate / compilescss), then the server is ready.

**Comment by jrief** [comment]
> I'd rather use Django's File Storage API, ignoring what storage backend it uses.

Then it should be simple:
* Add an event listener triggered after saving your SCSS file.
* Create a temporary file containing that content. It shall end in `.scss`.
* Use the function attached to the event handler to run `sass_processor`.
* Check that the path, where the compiled files are stored is somewhere accessible through a http-request.

**Comment by Natureshadow** [comment]
> > We cannot run compilescss before the database is available, i.e. at container/package build time
> 
> This problem sounds similar to the migration problem, and could be solved in the same way: deploy your code, then run a one-time command (migrate / compilescss), then the server is ready.

In contrast to the database, the filesystem of a sane deployment is read-only.

**Comment by Natureshadow** [comment]
>     * Check that the path, where the compiled files are stored is somewhere accessible through a http-request.

How would I make the `sass_processor` template tag generate a matcing URL? It seems to always use `STATIC_ROOT`.

**Comment by jrief** [comment]
Check the `render()`-function in `sass_processor/templatetags/sass_tags.py`. It takes a file and returns an URL.

Since your content is stored inside the database, it would be nice, if it could be compiled directly (ie. without using a file). I'm unsure if that's possible, I have to read though the sasslib-API.

**Comment by Natureshadow** [comment]
Well, it seems making the used storage class and its options configurable would be sufficient.

If you agree, I will make a PR.

**Comment by Natureshadow** [comment]
PR #147 enables this feature, plus quite a bit more. Please give feedback ☺!
