### ISSUE TITLE
sass_inline

### ISSUE THREAD

**Issue by ivictbor** [jrief/django-sass-processor#151]
Hey, thanks for a great lib!

How hard would it be to implement sass_inline tag? Maybe you already have something similar but undocumented?

Inline-styles are the must in handling some LCP/ FCP Web Vitals, because any CSS file load even with preload consumes double time  (imagine slow 3g networks with 2s delay, each request TTFB>=2s will end in >=4s of styles delivering, so need to deliver critical styles instantly)
For now, we use crunches to compile a file and then include them instantly saving 2s.

```
<!-- {% sass_src 'styles/everyPageInline_m.scss' %} -->
        <style>
            {% include 'styles/everyPageInline_m.css' %}
        </style>
``` 

But we want to use your great runtime compiler, especually reusing variables file which is common for instant and lazy files. Even without having CSS file in the end at all.

# Issue which forced me to ask

1. We have been using GitHub repo link in pip install, because had some issues with the old package (probable doc was not synced)
2. We have been using Manifested storage from the beginning.

But last 2 weeks all our projects started to experience next exception (in rendering phase, manage.py `compilescss` still works good):

```
ges/sass_processor/templatetags/sass_tags.py", line 42, in render
    return SassProcessor.handle_simple(path)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.8/site-packages/sass_processor/processor.py", line 144, in handle_simple
    return cls.storage.url(path)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 147, in url
    return self._url(self.stored_name, name, force)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 126, in _url
    hashed_name = hashed_name_func(*args)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 417, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'styles/everyPageInline_d.css'
```

I checked and the file exists in the manifest on the right place. I tried drill down in code and Manifest json file was empty at all: `{}` we started to dig down to OS `open(manifest_file)` and it turned out that it path was not correct (not static_root where it should be located)

Django version tried 3.1, 3.2, but it was not changed before and after bugs on several projects, so don't think is related.

# Our contribution

I am a founder of a Software development company https://devforth.io, and we use your project for all Django-based products for our clients plus all internal products. That is why, we recommend it to anyone who asks us, teach all our developers using it (everyone in tech nieche with other connections from tech universities), and also we leave mention in our blog posts, and install it to all our clients, if we can bring sass_inline, I think I would be able to popularize it and bring some star mass by other jucy posts about optimizations. No promises because you know how is it - priorities and time. But it definitely sits in my mind.

**Comment by ivictbor** [comment]
Tested `django-sass-processor===0.8.2` and manifested issue fixed.

**Comment by jrief** [comment]
The problem with inlining is, that you still have to create the file. That's what you do in your example. Then however that content always will be included into the rendered HTML, otherwise the browser will cache the generated CSS file.

If you have concerns about slow networks and additional requests, go ahead and use [django-compressor](https://django-compressor.readthedocs.io/en/stable/) with [django-sekizai](https://django-sekizai.readthedocs.io/en/latest/).

Another approach is to use HTTP/2.0, there all requests are handled by in the same TCP/IP session.

**Comment by Natureshadow** [comment]
I agree that inlining CSS is bad practice. The argument about network speeds does not hold, because the requested file will be cached (in constrast, it is transmitted over the wire for every single page load if inlined).

Encouraging such bad practice is beyond the scope of django-sass-processor, imho ;). Closing this issue as @jrief seems to agree.

**Comment by ivictbor** [comment]
> he argument about network

Where it would be cached? Are you aware of the Google Page speed insight and May 21 SEO update? It loads simulation with a clear cache like new user comes to read your content. The cache and simulates throttled network with big ping, so if you think you will cache CDN your ing to CDN will be still thtrottled and you will double request time

> I agree that inlining CSS is bad practice
I even don't know why you think so but it is an old best practice:
(copy you can google what is web dev and understand their role influence and role in tech)
https://web.dev/extract-critical-css/

![image](https://user-images.githubusercontent.com/1838656/114017435-acf07480-9874-11eb-975a-f78206f015a1.png)

Thoug HTTP 2 might solve it, but for me sounds like well-known and recommended inlines much simpler and more compatible approach

**Comment by Natureshadow** [comment]
>Where it would be cached? Are you aware of the Google Page speed insight and May 21 SEO update? It loads simulation with a clear cache like new user comes to read your content. The cache and simulates throttled network with big ping, so if you think you will cache CDN your ing to CDN will be still thtrottled and you will double request time

How many of the page loads made from your application are first page loads of new users?

I take it you have no links to other pages in your application, and the majority of users come once, look at one page, then leave? 

If that is the use case, then, and only then, inlining makes sense.

**Comment by ivictbor** [comment]
> How many of the page loads made from your application are first page loads of new users?
There are a lot of niches where it is critical like SEO.
Viral content, any marketing porpuses of Django websites wants EMPTY users, new users, new clients some of them will go down to funnel. Each new empty user might be bounced because of a white page duren several seconds. 
https://www.searchenginewatch.com/wp-content/uploads/sites/25/2018/07/think-with-Google.jpg

Well, if you wish to challenge your new "empty cache and mobile network" users or blog readers for patience before inviting to sail funnel then your are thinking right 😉

**Comment by Natureshadow** [comment]
> Well, if you wish to challenge your new "empty cache and mobile network" users or blog readers for patience before inviting to sail funnel then your are thinking right wink

Your argumentation might hold for websites that mainly deliver content (and if speed matters, really should be built into static pages instead of going through a full-blown Django…). I do not think that this is the scope of django-sass-processor — frameworks aiming at delivering content websites through Django will rely on SEO mechanisms, including inlining of content where it makes sense. We do not need t ocopy such functionality into django-sass-processor.
