### ISSUE TITLE
Invalid setting 'base_url' for S3StaticStorage (from django-storages)

### ISSUE THREAD

**Issue by TheRandomDog** [jrief/django-sass-processor#152]
Hey!

After updating this library and the django-storages library to their latest versions (1.0.0 and 1.11.1 respectively), I'm encountering an error from django-storages that seemed to have come from upgrading this library.

`django.core.exceptions.ImproperlyConfigured: Invalid setting 'base_url' for S3StaticStorage`

This also happens with the S3Boto3Storage recommended in the README. It seems to be a check in the [BaseStorage class of django-storages](https://github.com/jschneier/django-storages/blob/1.11.1/storages/base.py), and a recent change for 1.0.0 here might've started passing in keywords it wasn't expecting. (Looks like this one? https://github.com/jrief/django-sass-processor/commit/6e0f763f9c70f8fb48512ef1df153abbbbfe3012)

Not really sure what to make of it, or if I had even configured it correctly to being with (although it was working before). Thanks so much!

**Comment by Natureshadow** [comment]
Huh, I really missed that. I blindly assumed that the `S3StaticStorage` would immitate the interface of the default static storage. Sad it doesn't ;).

Can you please check if the branch in #153 fixes the issue?

**Comment by Natureshadow** [comment]
> Huh, I really missed that. I blindly assumed that the `S3StaticStorage` would immitate the interface of the default static storage. Sad it doesn't ;).

Then, why should it? No idea what I thought there.

**Comment by TheRandomDog** [comment]
Haha -- that branch does the trick, thanks for the quick response!

**Comment by Natureshadow** [comment]
I just released version 1.0.1 with the fix. Thanks for reporting!
