### ISSUE TITLE
Regression: Use of custom storages broken

### ISSUE THREAD

**Issue by Natureshadow** [jrief/django-sass-processor#159]
This change broke a lot of usecases (essentially all use cases that configure a dedicated storage for sass_processor):

https://github.com/jrief/django-sass-processor/pull/157/files#diff-35c6dc5cacbaf4e6db9adacd8dbbb338e0081cf26a9cc5c0c56c838ed938fe17R28

This happens because the `delivery_storage` is hard-coded to use `STATIC_FILES_STORAGE`.

@jrief Can you please look into it, and restore the prior behaviour, where the storage was configurable?

**Comment by Natureshadow** [comment]
Heads up: Version 1.1 was released to PyPI, effectively releasing a breaking change without honouring semantic versioning. All downstreams dependeing on `^1.0` and relying on this feature are now broken.

**Comment by Natureshadow** [comment]
In any case, @jrief, can you please folow up on this? @mauritsvanrees has long confirmed that the change that introduced the breakage is unnecessary. So why do we keep it?

**Comment by jrief** [comment]
@Natureshadow which commit are you talking about? Anyway, we use the `ManifestStaticFilesStorage` in our production
environment, and there version 1.1 runs as intended.

**Comment by Natureshadow** [comment]
django-sass-processor 1.2.1 has just accidentally landed in a production environment, which broke it because `sass_src` always looks for compiled CSS in the static storage instead of in the configured storage due to this change.
