### ISSUE TITLE
use of django_sass_processor without libsass

### ISSUE THREAD

**Issue by sylvainlb** [jrief/django-sass-processor#16]
In the documentation, you say 
```
libsass is not required on the production environment, if SASS/SCSS files have been precompiled and deployed using offline compilation.
```

I don't understand this sentence. If libsass is not installed on the server, the tag sass_src won't work because it raises an importError.

So how can we use django_sass_processor in the production environment without using this tag? Is there really a way to use django_sass_processor without libsass?

Thanks for your work!

**Comment by jrief** [comment]
Thanks for reporting, this somehow slipped through.

Please re-test in your environment and give me a notice, so that I can release 0.3.1

**Comment by sylvainlb** [comment]
Thank you for your patch!
Fyi, I had to add a {0} in the exception message to make compatible with python 2.

Besides that, maybe a better explanation of SASS_PROCESSOR_ENABLED in the readme would help.

Thanks a lot!

**Comment by jrief** [comment]
> Fyi, I had to add a {0} in the exception message to make compatible with python 2

Which Python do you use?
I use Py-2.7.10 all the time and ``"some text {}".format(variable)`` has never been for me.

Thanks for the hint with the explanation.

**Comment by sylvainlb** [comment]
You're right, the server actually uses python 2.6. It has been added in python 2.7

**Comment by jrief** [comment]
Oh, didn't know about that ``format`` restriction in Py-2.6.

BTW, please star this project.
