### ISSUE TITLE
Import-only files are not monitored for changes

### ISSUE THREAD

**Issue by Skynet0** [jrief/django-sass-processor#168]
I'm following approximately the 7-1 architecture suggested in https://sass-guidelin.es/#architecture. I often write new components, and have discovered that adding a new dependency by editing the import-only main does not cause a recompilation.

The reason is that [`is_latest` in `processor.py`](https://github.com/jrief/django-sass-processor/blob/2639eeda8722969b4286f8f95d5e7d41fd8fb6f2/sass_processor/processor.py#L63) checks the existing sourcemap, which doesn't include the main as a source, because it contains no CSS declarations (only imports). A workaround is to include a non-empty dummy rule in the file, such as

```css
.make-django-sass-processor-watch-this-file {
  display: none;
}
```

While you could monitor the base file, this doesn't catch import-only files that are deeper in the hierarchy.

**Comment by Skynet0** [comment]
My specific setup is something like

```
css/
  components/
    _button.scss
    _table.scss
  main.scss
```

Where `_button.scss` and `_table.scss` contain declarations, and `main.scss` contains

```scss
@import "components/button";
@import "components/table";
```

If I add a new component `_header.scss`, `main.scss` isn't in the sourcemap and therefore an added `@import` won't be picked up. The scenario you mentioned would likely run into the same general problem.

I don't have a clean solution off the top of my head, unfortunately. Some meh candidates:

- Add an optional "always recompile" argument to the tag (would solve the problem, but not elegantly)
- Specify extra files to watch for a particular `sass_src` (too long to put in the tag; feels clunky to do it in settings)

At the least, adding documentation for this behavior + a workaround would be appreciated.

**Comment by Skynet0** [comment]
Sounds right, yes. I'll open an issue against the other package as an FYI.

**Comment by jrief** [comment]
**django-sass-processor** shall be refactored towards dart-sass anyway. There are many nice features such as `@use` which are not supported by `libsass`.
