### ISSUE TITLE
Deprecation of STATICFILES_STORAGE in django 4.2

### ISSUE THREAD

**Issue by smoehrle** [jrief/django-sass-processor#169]
With the release of django 4.2 `STATICFILES_STORAGE` got deprecated in favor of `STORAGES["staticfiles"]` [1]

In the current version, django-sass-processor is not able to utiliize storage configured in the new format.

Old settings:
```
DEFAULT_FILE_STORAGE = "..."
STATICFILES_STORAGE = "..."
```

New settings:
```
STORAGES = {
    "default": {
        "BACKEND": "...",
    },
    "staticfiles": {
        "BACKEND": "...",
    },
}
```

[1] https://docs.djangoproject.com/en/dev/releases/4.2/#deprecated-features-4-2

**Comment by jrief** [comment]
Thanks for informing me.
