### ISSUE TITLE
Third party documentation no longer available

### ISSUE THREAD

**Issue by pau1a** [jrief/django-sass-processor#170]
On reading the Readme, at the bottom it says ;

"Brian wrote a nice artice on [how to easily use SASS/SCSS with Django](https://engineertodeveloper.com/how-to-easily-use-sass-scss-with-django/)."

This link is dead. Not sure if its moved or just gone away.

**Comment by jrief** [comment]
Thanks for reporting.

I'll wait a few day until removing that link. Could be that the server has some trouble.

**Comment by jrief** [comment]
Thanks for reporting again. This article unfortunately vanished from the Internet.

**Comment by merwok** [comment]
Article can be read here: https://web.archive.org/web/20210225201318/https://engineertodeveloper.com/how-to-easily-use-sass-scss-with-django/

**Comment by jrief** [comment]
I know, but I won't link onto articles on archive.org.

If you want, create a copy of that article on Medium and I will link on that.

**Comment by merwok** [comment]
Curious why you give more credit to a random copy by a random person on one blog platform than an archive of the original on the internet archive!

**Comment by Natureshadow** [comment]
I have long been questioning the qualities of @jrief as a FOSS maintainer, but this utterly stupid promotion of a commercial tracking platform settles it:

Please remove me as collaborator from this project.
