### ISSUE TITLE
Broken in Django 5.1 alpha due to get_storage_class

### ISSUE THREAD

**Issue by washeck** [jrief/django-sass-processor#175]
Version 1.3 claims `Remove usage of deprecated get_storage_class for Django >= 4.2.*.` but the fix is only partial.

The deprecated function is not used but it is imported on top of `storage.py`. Django 5.1 (in development now) removed this deprecated function making `django-sass-processor` fail with ImportError. The proper fix is to move the import line after the `if` for django version.

**Comment by washeck** [comment]
@jrief Thanks for merging https://github.com/jrief/django-sass-processor/pull/180

May I ask you to issue a new release with the fix? It would make my life a bit easier with testing our project for compatibility with the upcoming Django release.

**Comment by jrief** [comment]
What would you like me to add to the Changelog?

**Comment by washeck** [comment]
I think "Fix compatibility with Django 5.1dev" would be enough

**Comment by washeck** [comment]
Shall I prepare PR for the changelog entry? Now, when Django 5.1 alpha was released, the issue will become more visible.

**Comment by jrief** [comment]
Version 1.4.1 has been published:
https://pypi.org/project/django-sass-processor/
