### ISSUE TITLE
Installation via pip3 fails

### ISSUE THREAD

**Issue by sedrubal** [jrief/django-sass-processor#20]
I'm trying to install `django-sass-processor` via `pip3`, but I always get this error:

```python
Downloading/unpacking django-sass-processor
  Downloading django-sass-processor-0.3.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/django-sass-processor/setup.py) egg_info for package django-sass-processor
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/django-sass-processor/setup.py", line 39, in <module>
        long_description=convert('README.md', 'rst'),
      File "/tmp/pip_build_root/django-sass-processor/setup.py", line 11, in convert
        return fd.read()
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 782: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/django-sass-processor/setup.py", line 39, in <module>

    long_description=convert('README.md', 'rst'),

  File "/tmp/pip_build_root/django-sass-processor/setup.py", line 11, in convert

    return fd.read()

  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 782: ordinal not in range(128)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/django-sass-processor
Storing debug log for failure in /root/.pip/pip.log
```

But it's a bit strange: this only happens inside docker containers ([`fedora:23`](https://getfedora.org/de_CH/cloud/download/docker.html) and [`ubuntu:14.04`](https://hub.docker.com/_/ubuntu/)) but on my native `fedora 23` it is working fine. Can this problem be caused by missing dependencies? Do you know the dependencies?

And I read in # 18 that you 
> ... didn't expect it being wildly used.

I'm currently setting up a new Website. Should I use `django-sass-processor` or should I search for another project?

**Comment by jrief** [comment]
so you're using Python3, hmmm...
Did you install python-pandoc? If not, I'm sure its a stupid Py2-Py3 incompatibility. If you can fix it please send me a PR, I'm still using Py2. Try out with ``with open(filename, 'rb')`` or ``with open(filename, 'r')``. Not sure how Py3 reads text files.

> Should I use django-sass-processor or should I search for another project?

If you like it, please go ahead and star the project. I currently am using it for all of my new projects and I certainly will do so in the future. Its currently downloaded >1000 times per month from PyPI, so it seems to be useful.

**Comment by sedrubal** [comment]
Ah ok you're right: When I install `pandoc` (via `apt` or `dnf`) and `pypandoc` (`>=1.1.2` via `pip3`), it's working.
And with this patch it seems to work, too:

```diff
diff --git a/setup.py b/setup.py
index aaae259..1711877 100644
--- a/setup.py
+++ b/setup.py
@@ -7,8 +7,8 @@ try:
     from pypandoc import convert
 except ImportError:
     def convert(filename, fmt):
-        with open(filename) as fd:
-            return fd.read()
+        with open(filename, 'rb') as fd:
+            return str(fd.read())
 
 
 CLASSIFIERS = [
```

Unfortunately I don't know how to handle encodings correctly... I'll make a PR anyway :smile: 

> I am currently using it for all of my new projects and I certainly will do so in the future.

Great :+1:

**Comment by Zagrebelin** [comment]
You can just repace funny quotes in readme.md around `Compas` and `SASS`
> With this tool, you can safely remove your Ruby installations **“**Compass**”** and **“**SASS**”** from your Django)

to plain " double quote.

**Comment by sedrubal** [comment]
@jrief Thanks for merging :smiley: When are you planning to update the pypi repo?

@Zagrebelin lol :smile:
