### ISSUE TITLE
Can't install on non-English Windows.

### ISSUE THREAD

**Issue by Vovkt** [jrief/django-sass-processor#23]
Sorry for my English.
I have problem with installation.

Log:
C:\Users\MyUser\PycharmProjects\scss_test>pip install django-sass-processor
Collecting django-sass-processor
  Using cached django-sass-processor-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\MyUser\AppData\Local\Temp\pip-build-52so00wf\django-sass-processor\setup.py", line 39, in <module>
        long_description=convert('README.md', 'rst'),
      File "C:\Users\MyUser\AppData\Local\Temp\pip-build-52so00wf\django-sass-processor\setup.py", line 11, in convert
        return fd.read()
      File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 794: character maps to <undefined>
    ----------------------------------------
←[31mCommand "python setup.py egg_info" failed with error code 1 in C:\Users\MyUser\AppData\Local\Temp\pip-build-52so00wf\django-sass-processor←[0m

And I have a solution:
in setup.py need replace 
        with open(filename, 'r') as fd:
to
        with open(filename, 'r', encoding='UTF-8') as fd:

I already tried this on my fork and its work!

**Comment by jrief** [comment]
Thanks for reporting, I'll add a patch soon.

**Comment by jrief** [comment]
can you please install from github, ie

```
git clone https://github.com/jrief/django-sass-processor.git
cd django-sass-processor
pip install -e .
```

**Comment by Vovkt** [comment]
Thank! Its work!

C:\Users\MyUser\PycharmProjects\scss_test>pip install https://github.com/jrief/django-sass-processor/archive/master.zip
Collecting https://github.com/jrief/django-sass-processor/archive/master.zip
  Downloading https://github.com/jrief/django-sass-processor/archive/master.zip
←[K     / 16kB 110kB/ss
Installing collected packages: django-sass-processor
  Running setup.py install for django-sass-processor
Successfully installed django-sass-processor-0.3.0

**Comment by jrief** [comment]
Can you please retry with version 0.3.2 from PyPI, ie
```
pip uninstall django-sass-processor
pip install django-sass-processor
```

Thanks

**Comment by Vovkt** [comment]
C:\Users\MyUser\PycharmProjects\scss_test>pip install django-sass-processor
Collecting django-sass-processor
  Downloading django-sass-processor-0.3.2.tar.gz
Installing collected packages: django-sass-processor
  Running setup.py install for django-sass-processor
Successfully installed django-sass-processor-0.3.2
