### ISSUE TITLE
CSS files are not generated while rendering template

### ISSUE THREAD

**Issue by vhdmsm** [jrief/django-sass-processor#24]
There is a problem in generating css files while rendering templates so i have to use ```python manage.py compilescss``` everytime.
I've set all the settings and still it doesn't work, btw it's a mac osx v10.11.1.

**Comment by jrief** [comment]
Well, in my environment and in the environments of hundreds of other users it works. Therefore most likely it is a configuration issue. Whenever a template is rendered by Django, which contains a ``{% sass_src %}`` tag, the corresponding css file is generated and stored in a separate directory. Locate this directory and check if your static-file-finder finds those files.

**Comment by vhdmsm** [comment]
Well you're right, my configurations was located somewhere else and now it's working, sry for creating issue, maybe removing this issue is better.
