### ISSUE TITLE
Extensions for Jinja2 template support

### ISSUE THREAD

**Issue by AndreasBackx** [jrief/django-sass-processor#28]
The README mentions how to use the library for the commands, but there is no mention of it regarding templates. There doesn't seem to be an extension in the source, is there perhaps a function we can pass to the Jinja2 environment?

**Comment by jrief** [comment]
I haven't added the code to support, and I actually have never used Jinja2.
Would be great if you could dig through the code and add a few lines to the README file.

**Comment by AndreasBackx** [comment]
I'll definitely look through the code and try to get some work done in the coming days.

**Comment by jrief** [comment]
Sorry for not merging. I oversaw that PR.
