### ISSUE TITLE
Support for STATICFILES_DIRS

### ISSUE THREAD

**Issue by AndreasBackx** [jrief/django-sass-processor#31]
Currently SassFileStorage, a subclass of FileSystemStorage, is being used to pass to the CssFinder. There should be a way to get it to work with STATICFILES_DIRS so it looks in multiple folders. This would allow for a per-app scss/sass folder. I came across this while working on the Jinja extension.

**Comment by jrief** [comment]
But it does – at least in my setup.
I'm currently using two apps relying on sass-processor and they both are shipped with their own ``...scss`` files.

**Comment by AndreasBackx** [comment]
As far as I'm aware the output will be stored in either the static root or the specified sass root. I should've been more specific and that might be because this was very late (or early), but my idea was to output them in a path relative to the input SCSS-file.

```
root/
    app/
        scss/
            app.scss
        static/
            css/
                app.css
    app2/
        scss/
            app2.scss
        static/
            css/
                app2.css
```

Instead of:
```
root/
    app/
        scss/
            app.scss
    app2/
        scss/
            app2.scss
    static/
        css/
            app.css
            app2.css
```

Both `app/static`, `app2/static`, `app/scss`, and `app2/scss` would then be in `STATICFILES_DIRS`. Perhaps make `SASS_PROCESSOR_ROOT` possible to be a path relative to the source SCSS file?

**Comment by Auroch** [comment]
Do you have find a solution for obtaining this ?

**Comment by jrief** [comment]
I always keep my compiled files out of my projects, hence my ``STATIC_ROOT`` points onto that external folder. This prevents to have a mixture of hand written and autogenerated files. This also is the reason why you need ``STATICFILES_FINDERS = (..., 'sass_processor.finders.CssFinder', ...)``.

**Comment by jrief** [comment]
@AndreasBackx can I close this?

**Comment by AndreasBackx** [comment]
Ya, it's not that big of a deal.
