### ISSUE TITLE
CSS files don't load

### ISSUE THREAD

**Issue by ygwain** [jrief/django-sass-processor#34]
If there are no generated CSS files, they are generated but don't load after first dev server start (the browser get 404). Only after restarting dev server they load.
Django 1.9.3, django-sass-processor 0.3.4

**Comment by meedheym** [comment]
Would be awesome if this were to be fixed. On our test server we encounter this issue a lot...

**Comment by AndreasBackx** [comment]
@jrief do you know what causes this? I haven't come across this problem yet.

**Comment by jrief** [comment]
I actually can't reproduce it, so anybody who is able to reproduce this bug, please spend some time and investigate.

**Comment by udhaya0000** [comment]
While using with django-compressor, When Debug is False, it fails to compile the css. 
Ex:
DEBUG = False
TEMPLATE_DEBUG = False
COMPRESS_ENABLED = False

When COMPRESS_ENABLED is true it throughs 500 error.

**Comment by AndreasBackx** [comment]
@udhaya0000 when `DEBUG` is set to `False` then you have to compile it beforehand with the `compilescss` command. This is documented in the `README`. We are also gonna need more information than the status code. You probably configured it badly.

**Comment by udhaya0000** [comment]
@AndreasBackx Thanks `SASS_PROCESSOR_ENABLED = True` works, but `python manage.py compilescss` gives the following error `ImportError: Could not import settings 'app.settings.prod' (Is it on sys.path? Is there an import error in the settings file?): No module named unipath`

Also the collectstatic `PATTERN` not working if I use `.scss`, but it works if I change it to `*.scss`

**Comment by AndreasBackx** [comment]
@udhaya0000 please provide us with full stacktraces, exception messages are not worth much.

That pattern is working how it should...

**Comment by jrief** [comment]
@Arany reported that this happens if you invoke ``./manage.py collectstatic``, when the folder referenced by ``settings.STATIC_ROOT`` has not been created yet.

**Comment by RubeRuby** [comment]
It is an old issue, but I experience this too. 
First run:
![image](https://user-images.githubusercontent.com/21198758/35644605-af98ce5c-06c9-11e8-8a51-22d53d15773f.png)
Second run:
![image](https://user-images.githubusercontent.com/21198758/35644668-dc12d2e8-06c9-11e8-8d55-73635a2135f8.png)
