### ISSUE TITLE
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

### ISSUE THREAD

**Issue by hvu53** [jrief/django-sass-processor#38]
Im using django 1.9.5, & whenever I include the package in INSTALLED_APP, I got this error:

...site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by jrief** [comment]
Its most likely due to a configuration error.
This apps works in all of my projects.
