### ISSUE TITLE
`FileNotFoundError` not defined

### ISSUE THREAD

**Issue by robmoggach** [jrief/django-sass-processor#42]
Django 1.9+

    NameError at /
    global name 'FileNotFoundError' is not defined

    Exception Value:	 global name 'FileNotFoundError' is not defined

Here's the offender:

        templatetags/sass_tags.py
        38: except FileNotFoundError as e:

**Comment by robmoggach** [comment]
seems to be Python 2.7 related -

Inserting the following after the import statements in `sass_tags.py` reveals the underlying `CompileError`:

```
try:
    FileNotFoundError
except NameError:
    FileNotFoundError = IOError

```

**Comment by jrief** [comment]
Please retry. I then will release version 0.4.5

**Comment by robmoggach** [comment]
Works

**Comment by jrief** [comment]
Version 0.4.5 is available on PyPI.
Thanks for reporting.
