### ISSUE TITLE
css.map

### ISSUE THREAD

**Issue by hjjiang** [jrief/django-sass-processor#43]
is the "source" key suppose to be a relative directory?
{
    "version": 3,
    "file": "../../../../ui/static/scss/demo3.css",
    "sources": [
        "../../../../ui/static/scss/demo3.scss"
    ],
    "mappings": "AAEA,AAEU,UAFA,CACN,WAAW,CACP,EAAE,AAAA,OAAO,AAAC,CACN,KAAK,CALA,OAAO,CAMf",
    "names": []
}

**Comment by jrief** [comment]
This file is generated by libsass, not by django-sass-processor, therefore please refer to their documentation.
BTW, is this a problem for you?
