### ISSUE TITLE
Incompatibility with django-compressor 2.1

### ISSUE THREAD

**Issue by frostbtn** [jrief/django-sass-processor#45]
*django-compressor* released a [breaking change](https://github.com/django-compressor/django-compressor/commit/c0010bf2ae4064c11cfee2387f6e06c3880fc6d3#diff-01dc27e1db84256620f15d8a69b327caL119) to their interface from
`compressor.offline.django.DjangoParser.get_nodelist(self, node, original)`
to
`compressor.offline.django.DjangoParser.get_nodelist(self, node, original, context)`

so `sass_processor.management.commands.compilescss.Command.walk_nodes()` is now broken.

I see no easy way to make this change backward compatible with `django-compressor` <= 2.0 *and* Python 2, as the introspection API to get callable's signature was also changed. I suppose, the best course of actions is to ask `django-compressor` to make this `context` argument have a default value (`None`).

(I'm ended up with hard switching to compressor 2.1, as I no longer need 2.0 compatibility)

**Comment by jrief** [comment]
@frostbtn Thanks for reporting about this.
Would you mind to ask for this on the django-compressor's issue tracker, as I currently have no plans to upgrade to version 2.1.

**Comment by AndreasBackx** [comment]
@jrief there is [a check](https://github.com/django-compressor/django-compressor/commit/c0010bf2ae4064c11cfee2387f6e06c3880fc6d3#diff-01dc27e1db84256620f15d8a69b327caR123) whether context is None and if so it will create an empty Context. Right now the argument still requires it so we can update it by just giving it None.

**Comment by jrief** [comment]
yes we could ``try`` one alternative and if we catch a ``TypeError`` then proceed with the other one. I just created a branch to test this. @frostbtn could you please checkout branch ``compat-django-compressor-2.1`` and check in your environment.

**Comment by frostbtn** [comment]
@jrief Yes, this works correctly with 2.1. One wont call this beautiful, though. 
(H-ha, don't forget you've released 0.4.6, so no reason to base support branches on 0.4.5 :smile: - I needed this fix from 0.4.6 to check, wasn't a big problem indeed).
