### ISSUE TITLE
Please review branch auto-include-dirs

### ISSUE THREAD

**Issue by jrief** [jrief/django-sass-processor#46]
@AndreasBackx maybe this is an interesting new feature for version 0.5? Would you please be so kind and review it.

From the docs:

> Additionally, **django-sass-processor** will traverse all installed Django apps and look into their
> static folders. If any of them contain a file starting with a `_` (underscore) and ending in
> `.scss` or `.sass`, then that app specific static folder is added to the include paths.

**Comment by AndreasBackx** [comment]
I think it's best to move this to a PR. I left 1 comment on the commit, everything looks fine assuming it works.
