### ISSUE TITLE
Invalid template name in 'extends' tag

### ISSUE THREAD

**Issue by maltitco** [jrief/django-sass-processor#53]
compilescss give:

Invalid template name in 'extends' tag:

Error parsing template /Users/malt/Env/py3.5/lib/python3.5/site-packages/cms/templates/cms/dummy.html: Invalid template name in 'extends' tag: ''. Got this from the 'template' variable.

Error parsing template /Users/malt/Env/py3.5/lib/python3.5/site-packages/menus/templates/menu/dummy.html: Invalid template name in 'extends' tag: ''. Got this from the 'template' variable.

**Comment by jrief** [comment]
Apart from the error message, does it somehow impact your workflow?
The parsed templates are – as you can see – part of django-CMS, so outside of my scope.

You may always silence those errors by appending ``--verbosity=0``.
