### ISSUE TITLE
Jinja2 rises TemplateSyntaxError if a variable is passed

### ISSUE THREAD

**Issue by haloween** [jrief/django-sass-processor#54]
I have  a project that shares most of the template code base among few deployments.  To differentiate i set all the project template variables in a external file. When i pass a variable to  sass_src Exception is risen.

`
{% set PROJECT_SASS_FILE = 'xxx.scss' %}
{%if PROJECT_SASS_FILE%}
{% sass_src PROJECT_SASS_FILE %}
{%endif%}
`

**Comment by AndreasBackx** [comment]
Interesting, I'll have a look tonight or tomorrow and get back to you with my findings.

**Comment by int-ua** [comment]
I just tried creating a `sass` template tag for convenience and it's not working too with the error being 

    sass.html: 'NoneType' object has no attribute 'engine'

Code:

    {% load sass_tags %}
    <link rel="stylesheet"{% if media %} media="{{ media }}"{% endif %} href="{% sass_src static_url %}{% if version %}?{{ version }}{% endif %}">


    @register.inclusion_tag('meta/sass.html')
    def sass(static_url, version=None, media=None):
        return {
            'static_url': static_url,
            'version': version,
            'media': media,
        }

**Comment by jrief** [comment]
@haloween 
what is ``{% set PROJECT_SASS_FILE = 'xxx.scss' %}`` ?

did you intend something such as ``{% with ... %}``

**Comment by AndreasBackx** [comment]
@jrief it's Jinja2, see under [Assignments](http://jinja.pocoo.org/docs/2.9/templates/#assignments).

**Comment by jrief** [comment]
@AndreasBackx would you like to get write access to the repository so that you can handle all Jinja2 related issues. Since I don't use Jinja2 I really can't give any advise on it.

**Comment by AndreasBackx** [comment]
@jrief I don't mind. This issue is now fixed in #57.

**Comment by AndreasBackx** [comment]
@int-ua could you give us some testable code and perhaps a full stacktrace in a new issue?

**Comment by int-ua** [comment]
Yes, a little later, thank you.
