### ISSUE TITLE
Support for URL in STATIC_URL

### ISSUE THREAD

**Issue by Arany** [jrief/django-sass-processor#56]
I would like to serve static files from a subdomain, so normally I would set ``STATIC_URL = 'http://subdomain.example.com/``.
But this does not seem to work with the sass processor. It expects that the ``STATIC_URL`` is only a URL path without hostname.
The domain would still be served from the same machine (or they would be precompiled anyways), so it would only need to support the mapping from filename -> url.

**Comment by jrief** [comment]
From a quick look at the code, this seems to be a bug.

Just for my better understanding, this only is a problem during production, and not during development?

This means that ``./manage.py compilescss`` does not deploy correctly. One way to handle this, is to compile the .*scss files into .*css as siblings, so that they are located side by side in the same directory. Afterward deploy them using ``./manage.py collectstatic``.

**Comment by Arany** [comment]
No, this already happens in development mode, when I have the static files hosted already somewhere, as soon as I set the ``STATIC_URL`` to some complete url, it is not working.

For example, my file is at /static/css/base.scss, and i set the url to ``http://example.com/static``, then in the template, using ``sass_src``, it is translated just to `` /static/css/base.css``, which returns a 404 error.

**Comment by jrief** [comment]
Just tested locally by replacing ``STATIC_URL`` with ``http://localhost:8000/static/``. Inside the rendered HTML, the URLs start correctly with ``http://localhost:8000/static/...``, however Django's ``runserver`` doesn't deliver them.

The docs on https://docs.djangoproject.com/en/1.10/howto/static-files/#serving-static-files-in-development state:

> This helper function works only in debug mode and only if the given prefix is local (e.g. /static/) and not a URL (e.g. http://static.example.com/).

so using such a setting during development, probably is out of Django's use case.

**Comment by jrief** [comment]
@Arany can I close this?

**Comment by Arany** [comment]
Hm, okay. I guess I did something wrong, as i can now get it to work. Thx for the help anyways :-)
