### ISSUE TITLE
Issue with S3 storage using django-storages

### ISSUE THREAD

**Issue by cdriehuys** [jrief/django-sass-processor#62]
When attempting to store static files on S3 using the `django-storages` package, I get the following traceback.

```
Traceback (most recent call last):
  File "tutorial_site/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/virtualenvs/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/opt/virtualenvs/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/opt/virtualenvs/venv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/virtualenvs/venv/lib/python3.5/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/opt/virtualenvs/venv/lib/python3.5/site-packages/sass_processor/apps.py", line 24, in ready
    static_dir = os.path.join(app_config.path, self._storage.base_url.strip(os.path.sep))
AttributeError: 'S3Boto3Storage' object has no attribute 'base_url'
```

This appears to be caused by [this line](https://github.com/jrief/django-sass-processor/blob/master/sass_processor/apps.py#L24) in `apps.py` where the current storage class' `base_url` is accessed. The problem is the [`S3Boto3Storage` class](https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto3.py#L194) doesn't appear to define this attribute/property. 

Any help with this issue would be much appreciated.

**Comment by jrief** [comment]
@cdriehuys Please provide a pull request fixing this. Otherwise, please contact me on my private email address.

**Comment by cdriehuys** [comment]
Sorry for the delayed response. Unfortunately I don't have the time to make a pull request for this currently, but I appreciate you taking the time to look at this issue.

**Comment by jrief** [comment]
@cdriehuys If you can fund this feature, I can do it for you. Currently I have to plans to use AWS with S3, so it's not on my personal "to do" list.

**Comment by dgourley** [comment]
@cdriehuys I had a similar issue. You basically need to define your own storage class and define the base_url for your s3 configuration. Something like....

Set your own storage in our settings.py:

STATICFILES_STORAGE       = 'yourapp.storage.YourStorage'

Then define it in yourapp/storage.py:

from storages.backends.s3boto import S3BotoStorage

class YourStorage(S3BotoStorage):
    base_url = 'yourbucket.s3.amazonaws.com'

**Comment by jrief** [comment]
@dgourley I haven't been aware of this. Could you please add this to the README and open a pull request.

**Comment by dgourley** [comment]
@jrief will do. I just ran into this issue last night and found this as a workaround. Seems S3BotoStorage doesn't have base_url defined... easy enough to add the configuration. If you are using s3 you probably are defining a storage anyway to enable caching, manifest files, etc.

**Comment by cdriehuys** [comment]
@dgourley Thanks for the workaround. I avoided the issue by switching to a different build process, but I'll definitely use that solution on future projects.

**Comment by jrief** [comment]
@cdriehuys  Can this issue be closed then?

**Comment by cdriehuys** [comment]
Yes. I think the provided solution is easy enough to follow that this doesn't need to be fixed in the package itself.

**Comment by AlBlanc** [comment]
Actually the issue is: `django-sass-processor` is trying to read the `base_url`of each django apps storage classes.

But `base_url` is an attribute of `FileStorage`, so `django-sass-processor` assumes we must user a `FileStorage` and block us from using some other storage classes like one provided by `django-storages` which override `Storage` class (which is `FileStorage` superclass)

I really think a quick fix could help a lot of people. I'll try to take some time during this week to push a pull request. For the moment, i'll take the workaround above. Thank you!

**Comment by jrief** [comment]
@AlBlanc if you can fix this, it would be great. Currently I have no use-case for this, hence that's not on my priority list.
