### ISSUE TITLE
Integrating d-s-p with pip package containing django templates and sass_tags

### ISSUE THREAD

**Issue by AaronForce1** [jrief/django-sass-processor#65]
Hello!

Huge fan of your work here - as a full stack dev specializing in front end, I'm quite pleased to see the latest and greatest technologies being leveraged throughout more and more platforms.

I have a django project containing several apps, one of which is a _design_ app meant to house all the jinja2 templates, styles, javascript libraries - etc. We're planning to use this design app in several separate django projects within the same platform (base styles/shared templates/all that). I've managed to split out the design app into a self-sustained pip package but was having some issues with how `{% load sass_tags %}` works. Unfortunately it can't seem to parse the pip package template folder hierarchy correctly. Is there a setup I should be aware of? Any suggestions? I'd be happy to provide what I can in terms of source code for clarification.

Thanks so much!

**Comment by jrief** [comment]
Just follow the documentation.

**Comment by AaronForce1** [comment]
I did follow the documentation and it worked correctly until I moved the SASS files into a pip package. Now sass_src doesn't resolve paths within the design pip app. Can you provide more clarity and assistance?
