### ISSUE TITLE
input[type=url] {} does not compile

### ISSUE THREAD

**Issue by seanwhitehead** [jrief/django-sass-processor#67]
Error: property "input" must be followed by a ':'

I believe this is a regression

**Comment by seanwhitehead** [comment]
for anyone that comes across this from the interwebz, install django-compressor

**Comment by AndreasBackx** [comment]
Please provide source files and the full traceback. This sounds like a problem with your SASS code and not a problem with django-sass-processor.

**Comment by jrief** [comment]
@seanwhitehead please provide more information
