### ISSUE TITLE
 ImportError: No module named 'sass_processor'

### ISSUE THREAD

**Issue by raymestalez** [jrief/django-sass-processor#7]
Hi! I'm following the instructions in readme, I've succesfully installed django-sass-processor with pip, I'm trying to run server and getting the following error:

     ImportError: No module named 'sass_processor'

Am I missing something? What am I doing wrong?

**Comment by drivard** [comment]
could you execute the command line: pip freeze
then copy the output here please.

**Comment by YohannBethoule** [comment]
Hey there, I'm facnig the same problem and can't find any solution online, any help ?
