### ISSUE TITLE
Management command find_sources ignores SASS_PROCESSOR_AUTO_INCLUDE

### ISSUE THREAD

**Issue by eshellman** [jrief/django-sass-processor#70]
I would have thought that SASS_PROCESSOR_AUTO_INCLUDE = False would prevent the compilescss management command from looking in EVERY python source file for files to convert. But no, find_sources() looks everywhere, not just in APPS_INCLUDE_DIRS.

**Comment by jrief** [comment]
from rereading the code, it seems you're right.

**Comment by jsanchezs** [comment]
+1
