### ISSUE TITLE
absolute paths in css.map file

### ISSUE THREAD

**Issue by s-trooper** [jrief/django-sass-processor#72]
Hi, related to [64](https://github.com/jrief/django-sass-processor/issues/64) but only in parts. 

The problem is that `libsass` generates absolute paths in `css.map` file. I found that on Windows, but probably on *nix too, if `source_map_filename` parameter starts with root `/` slash  like `/static/base.css.map`  as it always the case because of this line: [L74](https://github.com/jrief/django-sass-processor/blob/43978f8c709d5f195229deb6ec7817a1815a4db6/sass_processor/processor.py#L74) `libsass` create absolute paths. If the `source_map_filename` starts without slash like `static/base.css.map` the generated paths would be relative as they should.

**Comment by jrief** [comment]
do you have a solution for that problem on Windows?

In my opinion, it's more a problem related to libsass itself, and not to this project.

**Comment by s-trooper** [comment]
I don't think its *problem* of libsass, they build css.map paths relative to source_map_filename and working directory, that just way it work. The Problem for this Project ist the ways Django resolve static resources in particular in DEBUG mode. 

For this specific issue a simple solution would be to replace `sourcemap_url = self.storage.url(sourcemap_filename)` with `sourcemap_url = self.storage.url(sourcemap_filename).lstrip("/")`, that would let libsass generate css.map paths relative to working directory. 

But djnago working directory is PROJECT_ROOT, so the relative paths would still dont work for the Browser as instead of "/static/app/base.css" the path would be "/app/static/app/base.css".

At the end i think as css.map is DEBUG feature of Chrome and the Problem is related to DEBUG mode of Django the best way ist to remove css.map generation at all ;). The "is_latest" check could be done of difference between scss source file and css target file.

P.S: i am curious for not Windows box, does css.map generation work in a way that a Browser can resolve paths in css.map file?

**Comment by jrief** [comment]
Since I don't use Windows, I would really appreciate, if you could add a patch to this project which can handle the DOS-styled file pathes.
I can't test it anyway.

**Comment by s-trooper** [comment]
I've spent some time investigating this issue and found that "absolute paths" are only part of the problem to get "css.map" work properly. My understanding of Django is not deep enough that I could generate properly "css.map", there are caching issues related, so I am going to close this issue as it is not Meanful for itself alone.
