### ISSUE TITLE
how to use SassS3Boto3Storage

### ISSUE THREAD

**Issue by eshellman** [jrief/django-sass-processor#74]
As far as I can tell, SassS3Boto3Storage is provided only for use as a django-sass-processor compatible STATICFILES_STORAGE. It isn't ever used for the SassProcessor. So in a deployment where it is desired for css files to be served by S3, the css files must first be generated into a FileSystemStorage (into writeable directories) and then moved to S3 by collectstatic, via STATICFILES_STORAGE using the sass-compatibility class. This seems like an non-intuitive way to integrate django storages, and may be hard to maintain. It would be better to instead use SassFileStorage as a compatibility layer around a configurable storage backend.

Perhaps documentation of this could be added.

**Comment by jrief** [comment]
I even use this workflow for my production services which do not run on AWS. First I compile, afterwards I deploy just as I would without sass-processor.

Unless I misunderstood something, what is your proposal to improve that?

**Comment by eshellman** [comment]
Adding the description to README would be enough. But it seems to me that having SassFileStorage extend Storage instead of FileSystemStorage would avoid the extra config step and would be a cleaner design.
