### ISSUE TITLE
Suggestion: remove libsass from install_requires

### ISSUE THREAD

**Issue by emirotin** [jrief/django-sass-processor#77]
Hi

The module docs say libsass is not required in production but the module declares it as its dependency.

I'm using pip-tools and the presence of libsass in setup.py makes it end up in my requirements.txt. This in turn means my dev env has to have buildtools (gcc, etc) installed.
This is inconvenient as I'm using docker and want my image to be as small as possible.

Should libsass be removed from setup.py as the docs already mention it has to be installed manually when needed?

**Comment by jrief** [comment]
Thanks for reporting.

**Comment by emirotin** [comment]
I've created a temp fork to immediately address my needs and once I was on it I decided I could also send a PR.
