### ISSUE TITLE
Help requested getting this to work

### ISSUE THREAD

**Issue by RubeRuby** [jrief/django-sass-processor#79]
I'm having trouble understanding the documentation fully, but this is what I did:
- Ran `pip install libsass django-compressor django-sass-processor`
- Added `'sass_processor',` in installed apps
- Debug is set to `True`
- Added `STATIC_ROOT = os.path.join(BASE_DIR, 'login/static/')` to the settings
- Put `{% load sass_tags %}` at the top of my template
- Put `<link href="{% sass_src 'login/scss/main.scss' %}" rel="stylesheet" type="text/css" />` in my template header
- Tried running python `./manage.py compilescss` which worked fine

From what I understand, if I run `python manage.py runserver` it should automatically compile my .scss files, yes? It is not generating anything, and is not spitting out any errors either.

Maybe I forgot a step?

**Comment by RubeRuby** [comment]
That seems to have done something, at least. However, if I add this code:
```
STATICFILES_FINDERS = [
    'sass_processor.finders.CssFinder',
]
```
to my settings file, it somehow prevents my styling files from being found. I tested this with a `.css` file which it could find okay, then I added these lines without editing the path of the `.css` and it somehow broke?

**Comment by RubeRuby** [comment]
It took me some time fiddling to realize 
```
'django.contrib.staticfiles.finders.FileSystemFinder',
'django.contrib.staticfiles.finders.AppDirectoriesFinder',
```
had to be added to that list too, but it works now. Thank you :)

**Comment by jrief** [comment]
> From what I understand, if I run python manage.py runserver it should automatically compile my .scss files, yes?

Did you set ``STATICFILES_FINDERS`` as described in the docs?
