### ISSUE TITLE
Will be able to use sass_processor() in django settings

### ISSUE THREAD

**Issue by aodarc** [jrief/django-sass-processor#82]
Hi!
Will be great to use sass_processor in settings to specify styles which are used for some setup CMS. 
For example I need configure some setting to use style on each pages, like this:
`ARCTIC_COMMON_MEDIA_ASSETS = {
    'css': {
        'all': sass_processor('styles/global.scss'),
    }
}`
But I can''t do this because I have the error "django.core.exceptions.ImproperlyConfigured" ...
And I found the solution to use django lazy function;

```
from django.utils.functional import lazy

def lazy_load_global_sass():
    """Lazy load sass_processor after settings ware configured"""
    from sass_processor.processor import sass_processor
    return sass_processor('styles/global.scss')

ARCTIC_COMMON_MEDIA_ASSETS = {
    'css': {
        'all': (lazy(lazy_load_global_sass, str)(),)
    }
}
```
BUT, when i want to compile scss offline,  'compilescss' command skip global.scss file,
because **FuncCallVisitor** can't count the lazy function calls to register this file to compile.

So, I suggest if it will be possible to create settings option where register the specific scss files to compile.

**Comment by jrief** [comment]
I could add that function to the parser. However, I would choose another name to be consistent with say ``ugettext`` which translates to ``ugettext_lazy`. Therefore such a function should be named ``sass_processor_lazy``.

You can create a pull request for it, but please add a unit test. Also, please test if it works using ``manage.py compilescss``. And add a small description. I do not fully understand, when this is required.

**Comment by jrief** [comment]
@aodarc I just had a second look at it.
What `compilescss` does, it to iterate over all Python files of a project and look for calls of the function `sass_processor`. Therefore you lazy call should work anyway. Did you test this?

**Comment by aodarc** [comment]
@jrief I looked into that and `compilescss` doesn't catch lazy call of sass_processor.

**Comment by jrief** [comment]
but it should catch the call of `sass_processor('styles/global.scss')`.

Just for your understanding: `compilescss` does not run any code of your project. Instead it makes a static code analysis and looks for function calls to `sass_processor(...)`.
