### ISSUE TITLE
Auto compile on production server

### ISSUE THREAD

**Issue by RoscaS** [jrief/django-sass-processor#85]
Hi,

There must be something that I skipped but I can't make it work on a live server although it's working perfectly locally.

I'm pretty sure that the issue is that the auto compiling is not kicking in because if I manually trigger it (`./manage.py compilescss`) the new css is spitted out. It's also working if I set `DEBUG` to `True`. Any idea that could help me solve this?

Cheers

**Comment by jrief** [comment]
Did you run `./manage.py collectstatic` after running `./manage.py compilescss`?

**Comment by RoscaS** [comment]
Hey Jacob,

I tried both with no success.

**Comment by jrief** [comment]
In production, are the generated `.css` files side by side with the `.scss` sources, aka. in the same directory?

**Comment by jrief** [comment]
Did you create the folder where collectstatic afterwards will drop the files?
Other suggestion is to use django-compressor and concatenate all css files into one big file.

**Comment by RoscaS** [comment]
First sorry that I didn't get back to you quicker.

So, yes both files are in the same directory and `collecstatic` is doing his job fine. I gonna give it a spin with a new project tomorrow and we'll see if it works there.

**Comment by elmcrest** [comment]
this sounds to me that @RoscaS want's to use the live compilation on production, or am I wrong?

I was thinking about that too, with that it should be cool to let users play around with their prefered colors for example :smile:
