### ISSUE TITLE
Compressed file does not contain imported compressed scss files

### ISSUE THREAD

**Issue by kmazi** [jrief/django-sass-processor#86]
The outputted css file does not contain other linked .scss files imported in the main .scss file loaded using the sass_src template tag. It only compiles sass code written in the referenced .scss file but partially ignores other imported .scss files in the referenced .scss file.

**Comment by jrief** [comment]
If its a SASS compiler issue, then this is the wrong place to ask for help.
Please learn how to write reproducible bug reports.

**Comment by kmazi** [comment]
Ok noted. I thought it was an issue with the template tag. It compiles correctly when the linked scss file loaded by the `sass_src` tag contains no reference to other scss files via the @import command. However, when other scss files are imported into the main scss file, they are not compile. Is that the expected behaviour of the django-sass-processor? For example: 
```
{% load sass_tags %}
<link rel="stylesheet" href="{% sass_src "homepage/css/custom.scss" %}">
```
The custom.scss file outputs the right css file with it's mapping but when other scss files are imported within custom.scss, they are not converted to css even though the .css.map file points to the location of the other scss files.

**Comment by jrief** [comment]
> However, when other scss files are imported into the main scss file, they are not compile. Is that the expected behaviour of the django-sass-processor?

This is intended behaviour of libsass, not django-sass-processor. And yes, if you `@import` other SCSS files into yours, yes, then this is considered as import of the sources which are only compiled into `custom.css`.

**Comment by kmazi** [comment]
That's the point; the imported sources are not compiled into custom.css. Thanks for your response though.
