### ISSUE TITLE
“sass.CompileError: Error: It's not clear which file to import” error when running the `compilescss` command

### ISSUE THREAD

**Issue by khpeek** [jrief/django-sass-processor#87]
As I've also described in the [StackOverflow question](https://stackoverflow.com/questions/49786406/sass-compileerror-error-its-not-clear-which-file-to-import-arising-when-usi), I have a template that starts like this:

```
{% load compress %}
{% load sass_tags %}

<html>
  <head>
    {% compress css %}
    <link href="{% sass_src 'stylesheets/vendor/materialize_v1.scss' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'stylesheets/terms_of_use.scss' %}" rel="stylesheet" type="text/css" />
    {% endcompress %}
```

The `terms_of_use.scss` file imports `materialize_v1`, like so:

```
@import "vendor/materialize_v1";    // Materialize v1.0.0beta
```

However, when I run `python manage.py compilescss`, I get the following error:

```
sass.CompileError: Error: It's not clear which file to import for '@import "vendor/materialize_v1"'.
       Candidates:
         vendor/materialize_v1.scss
         vendor/materialize_v1.css
       Please delete or rename all but one of these files.
        on line 1 of lucy_web/static/stylesheets/terms_of_use.scss
>> @import "vendor/materialize_v1";    // Materialize v1.0.0beta
   ^
```

It seems like it is first compiling `materialize_v1.scss`, after which the `@import` statement becomes ambiguous. Is this indeed what's happening? Should the SASS processor not ideally be 'smart enough' to see that `materialize_v1` is imported in `terms_of_use.scss`, and therefore compile it last?

**Comment by jrief** [comment]
You should rename `vendor/materialize_v1.scss` to `vendor/_materialize_v1.scss`. This prevents compiling of files intended for inclusion into other scss files.

It doesn't make sense anyway to refer to `vendor/materialize_v1.scss` from HTML and later on include it a second time into `stylesheets/terms_of_use.scss`, so remove the first `<link href="{% sass_src 'stylesheets/vendor/materialize_v1.scss' %}" rel="stylesheet" type="text/css" />`.

**Comment by jrief** [comment]
just cross-posted my answer on Stackoverflow.
