### ISSUE TITLE
Django Foundation 6 does not auto compile

### ISSUE THREAD

**Issue by source3** [jrief/django-sass-processor#89]
To recompile scss I have to run `python manage.py compilescss` .  Deleting the static files does not recompile. Refreshing the page without using cache makes no difference.  

I have read through the closed issues and it seams that the scss files should autocompile.  
Any thoughts?

The directory structure is:
.
├── foundation
│   ├── assets
│   ├── customizer
│   ├── dist
│   ├── js
│   ├── node_modules
│   ├── scss
│   └── _vendor
├── fudrr
│   ├── __pycache__
│   └── static
├── home
│   ├── migrations
│   ├── __pycache__
│   └── templates
├── media
├── polls
│   ├── migrations
│   ├── __pycache__
│   └── templates
├── static
│   └── admin
└── templates

The foundation.scss file in ./foundation/assets imports from ./foundation/scss.  It makes no difference, as far as I can tell, if I point `SASS_PROCESSOR_INCLUDE_DIRS` and `STATICFILES_DIRS` to either of the two previously referenced foundation folders.  I am editing the `./foundation/scss/_global.scss` file.

I have set to `DEBUG=True`
Below is a portion of the settings.py:

>""" **************
>BASE_DIR point to "/code", which is a volume on Docker.  /code contains the
>django app.
>************** """
>
>INSTALLED_APPS = [
>   ...
>    'django.contrib.staticfiles',
>    'sass_processor',
>   ...
>]
>
>STATICFILES_FINDERS = [
>    'django.contrib.staticfiles.finders.FileSystemFinder',
>   'django.contrib.staticfiles.finders.AppDirectoriesFinder',
>    'sass_processor.finders.CssFinder',
>]
>
>STATIC_ROOT = os.path.join(BASE_DIR, 'static') # /code/static
>STATIC_URL = '/static/'
>
> """ Changes are being made to foundation/scss/_global.scss"""
>SASS_PROCESSOR_INCLUDE_DIRS = [
>    os.path.join(BASE_DIR, 'foundation/scss'),
>]
>
>STATICFILES_DIRS = [
>    os.path.join(BASE_DIR, 'foundation/assets'),
>]
>
>SASS_PROCESSOR_ENABLED = True

And base.html located in ./templates:

`<link href="{% sass_src 'foundation.scss' %}" rel="stylesheet" type="text/css" />`

**Comment by jrief** [comment]
`python manage.py compilescss` adds the compiled `.css` files side by side with the source `.scss` files. Afterwards `python manage.py collectstatic` copies them to their final destination. Therefore it makes no difference, if you delete them or not.
Please recheck.
Also remember, as soon as a scss-file is found and compiled by `libsass`, this app has nothing to do with it anymore.

**Comment by source3** [comment]
Ah, I thought django-sass-processor would automatically compile the .scss files anytime the .scss file is changed and the webpage is reloaded.  So, every time I update the .scss file during development/design I run `python manage.py compilescss` to recompile the .scss.  Then refresh the webpage to convert the .scss into .css and place in static directory .  Then when ready for production run `python manage.py compilescss` followed by `python manage.py collectstatic`.

Only refreshing the change after an update to .scss without `python manage.py compilescss` will not recompile the scss, just copy the existing .css into the static folder.

If this is correct, please close this issue.  And thank you for developing this app.  It is great not have to run gulp too.

**Comment by jrief** [comment]
> So, every time I update the .scss file during development/design I run python manage.py compilescss to recompile the .scss.

No, during development, if `DEBUG = True`, .scss files are compiled automatically. They are stored outside of your working directory, usually in `STATIC_ROOT`.

> Only refreshing the change after an update to .scss without python manage.py compilescss will not recompile the scss, just copy the existing .css into the static folder.

Sure it does! Otherwise you have a configuration problem.

**Comment by jrief** [comment]
can I close this?

**Comment by source3** [comment]
Yes. Thank you. 

Andrew Parker
Source3 Computing
Durango, CO
970-570-9535
