### ISSUE TITLE
The processor is taking too much time to show the changes locally.

### ISSUE THREAD

**Issue by pilarfc** [jrief/django-sass-processor#91]
Hello! First of all thanks for this amazing tool, is super helpful. 

However I have been dealing with an issue the past days. Sometimes when I update something, it took a lot of time (once, an entire day) to show the changes that I already applied to an element. Does is this a normal behavior?  I checked my logs and also run the server again, and nothing. I just have too wait and see the changes later.

**Comment by jrief** [comment]
No, normally sass-processor should regenerate the file as soon as its source SCSS or and includes change. This is handled by a list of dependencies added to the sourcemap file, generated together with the css file.

In case you can't figure out, add a breakpoint to method `SassProcessor.is_latest()` and try to figure out what the problem could be.
