### ISSUE TITLE
If any python source file has any syntax error, compilescss fails in a way that hides the source of the problem

### ISSUE THREAD

**Issue by jamezpolley** [jrief/django-sass-processor#93]
* during compilescss, every python file in the project is parsed by ast.py just in case it *might* invoke `sass_processor`
* This makes compilescss break if there is any syntax error inside any of those files
* Granted, there probably shouldn't be syntax errors in those files...
* But it's possible to have, for instance, a syntax error in a code path that's never hit in production
* These syntax errors are thus never a problem - until we run compilescss and get a syntax error.

Even worse, the error output that results is so unfathomable that #92 was misdiagnosed as being "a bug in ast.py"; as far as I can tell, it's not a bug in ast.py, it's a syntax error in some other file which would never have been noticed if we weren't asking ast.py to parse the whole file.

https://github.com/jrief/django-sass-processor/blob/c9f546d39f270a4ffa8aefabd93c328f59b891c4/sass_processor/management/commands/compilescss.py#L153

I'm not sure what to do as a permanent fix here; perhaps we can be more selective about which files to parse; or perhaps catch the syntax error and continue?

As a stopgap, I'm going to suggest a patch which would at least be more verbose about which file has the syntax error, to help make it easier to find the source of problems.

**Comment by jrief** [comment]
This is a good point. I never encountered this problem, because I never shipped code with syntax errors to my production systems and did not think about this possibility.

Thanks for the pull request.
