### ISSUE TITLE
django-sass-processor is changing the order of the css rules

### ISSUE THREAD

**Issue by narunask** [jrief/django-sass-processor#97]
The following `main.scss`:

    @import "./boostrap-custom";
    @import "./custom_styles";

Accompanied with the `html`:

    <link rel="stylesheet" type="text/css" href="{% sass_src 'scss/main.scss' %}">

Compiles to the following `css` rules:

[![combined scss][1]][1]

---

However if I reference aforementioned `scss` files separately, I get different `css`:

    <link rel="stylesheet" type="text/css" href="{% sass_src 'scss/boostrap-custom.scss' %}">
    <link rel="stylesheet" type="text/css" href="{% sass_src 'scss/custom_styles.scss' %}">

[![separate scss][2]][2]

Note that `_spacing.scss` and `essentials.css` swap around places. Hence it seems that `django-sass-processor` plugin is using some internal logic which doesn't work very well in my case.

Any ideas how I may resolve this?

  [1]: https://i.stack.imgur.com/mZqOY.png
  [2]: https://i.stack.imgur.com/xezjG.png

**Comment by jrief** [comment]
This must be related to the compiler itself. django-sass-processor does not interfere with the SCSS code itself.

Closing this, because it's unrelated.
