### ISSUE TITLE
SASS_PROCESSOR_ENABLED setting giving a hard time

### ISSUE THREAD

**Issue by vovimayhem** [jrief/django-sass-processor#98]
I was trying to use the sass precompilation for a deployable docker image.

Even when running `python manage.py compilescss && python manage.py collectstatic --ignore=*.scss`, I spent hours watching how the app didn't find the compiled css file...

...until I finally took a look at the processor.py file. Turns out it was tripping out because the `.map` was missing, and the `SASS_PROCESSOR_ENABLED` setting wasn't set to `False`.

Although there's a mention of `SASS_PROCESSOR_ENABLED` in the README file, it is not really evident at all you need to set this setting to `False` in order for the `sass_src` helper to work on production environments... Maybe we should add a section about precompiled assets in production environments?

**Comment by jrief** [comment]
The default setting for `SASS_PROCESSOR_ENABLED` is the same as `DEBUG`. Therefore, unless you set `DEBUG = True` in production (hope, you don't :)), this should just work.
In my projects, I usually do not set this variable in my `settings.py`.

**Comment by vovimayhem** [comment]
OMG got it!
