### ISSUE TITLE
Run post-process at the end of compilescss

### ISSUE THREAD

**Issue by astronouth7303** [jrief/django-sass-processor#99]
When using django-sass-processor with [WhiteNoise](http://whitenoise.evans.io/en/stable/) (specifically, the hashed/manifest storage option), the generated CSS files are not hashed, likely because static post-processing doesn't happen.

This is an essential part of far-future caching options.

**Comment by jrief** [comment]
Could you please point me onto some documentation, what has to be done.
PRs are always welcomed.

**Comment by astronouth7303** [comment]
That's... complicated.

So the goal is to have the final URLs in production to contain a hash, so the URL changes if the file changes. Far future cache expirations etc etc.

staticfiles provides this as a feature, via the [post-process step](https://github.com/django/django/blob/38cada7c94f5f73d2d47a0a730ea5d71d266fa2c/django/contrib/staticfiles/storage.py#L208) in some of its backends (including major backends of WhiteNoise). This is called by [collectstatic](https://github.com/django/django/blob/38cada7c94f5f73d2d47a0a730ea5d71d266fa2c/django/contrib/staticfiles/management/commands/collectstatic.py#L126).

Unfortunately, I'm looking at this and I'm not sure how doing this hashing in two commands will mix? Like, will it work ok if it's collecting files in two different commands? Like, I'm looking at projects like StaticfilesPlus to fill in that gap.

**Comment by jrief** [comment]
@astronouth7303 actually, that's what I do:
I use django-sekizai and wrap all `{% sass_src ... %}` into `{% addtoblock "css" %}`.
Then together with django-compressor, these files are concatenated, optionally compressed and the output files is renamed using a unique hash.

The drawback of this is that it's done during running the server, not while invoking `collectstatic`.
